### ISSUE TITLE
svg element has no viewport

### ISSUE THREAD

**Issue by thomsa89** [bpmn-io/bower-bpmn-js#6]
Hi there,

When I create the svg the height and width is set to 100%. The parent of the svg is set so it gets the height from the elements inside of it.
Now my problem is that the graphic is cut of becouse the container doesn't get the right height. This problem should be solved when the svg gets an viewbox attribute.
I created an jsfiddle where my Problem is showen: https://jsfiddle.net/pcmq55t1/1/. Note that in our project there is no possibility to zoom or move the grafic like it is in the fiddle.

 greetings Thomas

**Comment by ricardomatias** [comment]
Hey @thomsa89,

it's part of the SVG standard that the container of the SVG needs to have a explicit height in pixels. You can try setting a height of 600px on .accordion-body and seeing the result. 
Also if you want the diagram to fit the container through the internal zoom feature, you have to attach an event listener so that when the accordion gets opened the zoom level is set to `fit-viewport`.
